name: base
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
  - conda-forge
dependencies:
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39haa95532_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - backoff=2.2.1=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=py39haa95532_0
  - blas=1.0=mkl
  - bleach=6.0.0=pyhd8ed1ab_0
  - bokeh=2.4.3=py39haa95532_0
  - boltons=23.0.0=py39haa95532_0
  - boto3=1.26.99=pyhd8ed1ab_0
  - botocore=1.29.99=pyhd8ed1ab_0
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - bs4=4.11.1=hd3eb1b0_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - click=8.0.4=py39haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - coiled=0.5.7=pyhd8ed1ab_0
  - colorama=0.4.6=py39haa95532_0
  - conda=23.3.1=py39haa95532_0
  - conda-package-handling=1.9.0=py39h09fa780_1
  - cryptography=39.0.1=py39h21b164f_0
  - cudatoolkit=11.0.221=h74a9793_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py39h2bbff1b_0
  - dask-core=2022.2.1=pyhd3eb1b0_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - faiss=1.7.1=py39cuda110h2b1c9a6_1_cuda
  - faiss-gpu=1.7.1=h278398d_1
  - fftw=3.3.9=h2bbff1b_1
  - filelock=3.10.6=pyhd8ed1ab_0
  - flask=2.2.2=py39haa95532_0
  - flask-login=0.6.2=py39haa95532_0
  - freetds=1.3.3=hcd4344a_0
  - freetype=2.10.4=hd328e21_0
  - frozenlist=1.3.3=py39h2bbff1b_0
  - fsspec=2023.3.0=py39haa95532_0
  - future=0.18.3=py39haa95532_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py39haa95532_0
  - ijson=3.1.4=py39h2bbff1b_1
  - importlib_metadata=6.1.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.10.0=py39haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.5=pyhd8ed1ab_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jedi=0.18.1=py39haa95532_1
  - jinja2=3.1.2=py39haa95532_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.1.1=py39haa95532_0
  - jpeg=9b=hb83a4c4_2
  - jsondiff=2.0.0=pyhd8ed1ab_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.1.0=py39haa95532_0
  - jupyter_core=5.3.0=py39haa95532_0
  - jupyter_server=1.23.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.6=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39hd77b12b_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=12.0.0=default_h627e005_2
  - libdeflate=1.17=h2bbff1b_0
  - libfaiss=1.7.1=cuda110hfdcb733_1_cuda
  - libfaiss-avx2=1.7.1=cuda110h1234567_1_cuda
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.0=h8a3f274_0
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - locket=1.0.0=py39haa95532_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib-base=3.5.3=py39h581301d_0
  - matplotlib-inline=0.1.6=py39haa95532_0
  - mdurl=0.1.0=py39haa95532_0
  - menuinst=1.4.19=py39h59b6b97_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - msgpack-python=1.0.3=py39h59b6b97_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - nb_conda=2.2.1=win_6
  - nb_conda_kernels=2.3.1=py39haa95532_0
  - nbclassic=0.5.3=pyhb4ecaf3_3
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=py39haa95532_0
  - ninja=1.7.2=0
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=py39haa95532_0
  - openssl=1.1.1t=h2bbff1b_0
  - pandoc=1.19.2.1=1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.0.1=py39haa95532_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=py39haa95532_0
  - plotly=5.9.0=py39haa95532_0
  - pluggy=1.0.0=py39haa95532_1
  - ply=3.11=py39haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=py39haa95532_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.10.0=py39haa95532_0
  - pycosat=0.6.4=py39h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pymssql=2.2.5=py39h2bbff1b_0
  - pymysql=1.0.2=py39haa95532_1
  - pyodbc=4.0.34=py39hd77b12b_0
  - pyopenssl=23.0.0=py39haa95532_0
  - pyparsing=3.0.9=py39haa95532_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyqt5-sip=12.11.0=py39hd77b12b_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.16=h6244533_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.7.1=py3.9_cuda110_cudnn8_0
  - pywin32=305=py39h2bbff1b_0
  - pywinpty=2.0.10=py39h5da7b33_0
  - pyyaml=6.0=py39h2bbff1b_1
  - pyzmq=23.2.0=py39hd77b12b_0
  - qt=5.9.7=vc14h73c81de_0
  - reportlab=3.6.12=py39h2bbff1b_0
  - requests=2.28.1=py39haa95532_1
  - ruamel.yaml=0.17.21=py39h2bbff1b_0
  - ruamel.yaml.clib=0.2.7=py39ha55989b_1
  - s3transfer=0.6.0=py39haa95532_0
  - scikit-learn=1.2.2=py39hd77b12b_0
  - scipy=1.10.0=py39h321e85e_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=67.6.1=pyhd8ed1ab_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=py39haa95532_0
  - spacy-loggers=1.0.1=pyhd3eb1b0_0
  - sqlalchemy=1.4.39=py39h2bbff1b_0
  - sqlite=3.41.1=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py39haa95532_1
  - terminado=0.17.1=py39haa95532_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py39haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py39haa95532_0
  - tornado=6.2=py39h2bbff1b_0
  - tqdm=4.65.0=py39hd4e2768_0
  - traitlets=5.7.1=py39haa95532_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - ucrt=10.0.20348.0=haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wasabi=0.9.1=py39haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - werkzeug=2.2.3=py39haa95532_0
  - wheel=0.38.4=py39haa95532_0
  - widgetsnbextension=4.0.6=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - winpty=0.4.3=4
  - xz=5.2.10=h8cc25b3_1
  - yajl=2.1.0=vc14h2bbff1b_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=hd77b12b_0
  - zict=2.1.0=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
      - adjusttext==0.8
      - aiohttp==3.8.4
      - altair==4.2.0
      - attrs==22.1.0
      - bcrypt==4.0.1
      - blinker==1.5
      - branca==0.6.0
      - brotli==1.0.9
      - cachetools==5.2.0
      - charset-normalizer==2.1.1
      - commonmark==0.9.1
      - contourpy==1.0.7
      - cssselect2==0.7.0
      - dask==2023.3.2
      - deprecation==2.1.0
      - distributed==2023.3.2
      - docopt==0.6.2
      - extra-streamlit-components==0.1.56
      - faker==17.6.0
      - favicon==0.7.0
      - folium==0.14.0
      - fonttools==4.38.0
      - geographiclib==2.0
      - geopy==2.3.0
      - gevent==22.10.2
      - gitdb==4.0.10
      - gitpython==3.1.29
      - greenlet==2.0.2
      - h11==0.14.0
      - htbuilder==0.6.1
      - html5lib==1.1
      - httpcore==0.16.3
      - httpx==0.23.3
      - huggingface-hub==0.13.3
      - importlib-metadata==5.1.0
      - install==1.3.5
      - jsonpickle==3.0.1
      - jsonschema==4.17.1
      - lxml==4.9.2
      - lz4==4.3.2
      - markdown==3.4.1
      - markdownlit==0.0.5
      - matplotlib==3.6.3
      - more-itertools==9.1.0
      - multidict==6.0.4
      - networks==0.3.7
      - networkx==3.0
      - nltk==3.8.1
      - numpy==1.23.5
      - packaging==21.3
      - pandas==1.5.2
      - pdf2image==1.16.3
      - pillow==9.4.0
      - pipreqs==0.4.11
      - protobuf==3.20.3
      - pyarrow==11.0.0
      - pydantic==1.8.2
      - pydeck==0.8.0
      - pydyf==0.5.0
      - pygments==2.13.0
      - pyjwt==2.6.0
      - pymdown-extensions==9.10
      - pympler==1.0.1
      - pyperclip==1.8.2
      - pyphen==0.13.2
      - pyrsistent==0.19.2
      - python-decouple==3.7
      - pytz==2022.6
      - pytz-deprecation-shim==0.1.0.post0
      - regex==2023.3.23
      - rfc3986==1.5.0
      - rich==12.6.0
      - semver==2.13.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.97
      - sklearn==0.0.post1
      - smmap==5.0.0
      - spacy==3.0.9
      - st-annotated-text==3.0.0
      - streamlit==1.15.1
      - streamlit-aggrid==0.3.3
      - streamlit-authenticator==0.2.1
      - streamlit-book==0.7.5
      - streamlit-camera-input-live==0.2.0
      - streamlit-card==0.0.4
      - streamlit-cookies-manager==0.2.0
      - streamlit-elements==0.1.0
      - streamlit-embedcode==0.1.2
      - streamlit-extras==0.2.6
      - streamlit-faker==0.0.2
      - streamlit-folium==0.11.0
      - streamlit-image-coordinates==0.1.3
      - streamlit-keyup==0.2.0
      - streamlit-login-auth-ui==0.2.0
      - streamlit-lottie==0.0.3
      - streamlit-modal==0.1.0
      - streamlit-option-menu==0.3.2
      - streamlit-toggle-switch==1.0.2
      - streamlit-vertical-slider==1.0.2
      - tokenizers==0.13.2
      - torchaudio==0.7.2
      - torchvision==0.8.2+cu110
      - transformers==4.27.4
      - trycourier==4.4.0
      - typer==0.3.2
      - tzdata==2022.6
      - tzlocal==4.2
      - urllib3==1.26.12
      - validators==0.20.0
      - watchdog==2.1.9
      - weasyprint==58.0
      - webencodings==0.5.1
      - wordcloud==1.8.2.2
      - yarg==0.1.9
      - yarl==1.8.2
      - zipp==3.10.0
      - zope-event==4.6
      - zope-interface==5.5.2
      - zopfli==0.2.2
prefix: D:\Anaconda\envs\ScholarPortrait
